### PR TITLE
Provides a way to disable adding headers automatically

### PR DESCRIPTION
**Pull request by thefosk**
Currently the system adds some headers automatically. I would like to provide a way to disable this behavior by introducing a `disable_auto_headers` boolean param that can be set when requesting a resource.

Also addresses #71.

### CODE REVIEW

**Comment by pintsized** [comment]
Hey, thanks for this.

Can you explain the use case a little more? I mean, I understand what it does, but why is it useful to you?

**Comment by thefosk** [comment]
I am using your client to execute HTTP integration testing on my software, and being able to disable this feature allows me to control exactly how the request will be performed in any edge-case.

**Comment by pintsized** [comment]
Yeah, I just don't really feel comfortable adding a supported feature to make a bad request. You could use ngx_lua cosockets directly perhaps, borrowing parts of lua-resty-http as utilities? But I'd prefer this library tries to work correctly and robustly in all cases - an option here isn't generally useful for anything other than making bad requests as far as I can see?

Not trying to shut it down - if you think I'm wrong in making assumptions with request headers then do say as I could well be wrong here (and it's been a while since I looked at it).

**Comment by thefosk** [comment]
I understand your point and it totally makes sense. I ultimately agree this shouldn't be a parameter, and, if implemented, it could perhaps be a method like `request_raw(..)`.

**Comment by pintsized** [comment]
You could just send your raw request down the wire manually, and then use lua-resty-http to read the response.

```lua
 local httpc_mod = require "resty.http"
 local httpc = httpc_mod.new()
 httpc:connect("127.0.0.1", 80)
 local bytes, err = httpc.sock:send("GET /HTTP/1.1\nHost: example.com\n\n")
 if not bytes then
     ngx.log(ngx.ERR, err)
 end

 local res, err = httpc:read_response({ headers = {} })
 if not res then
     ngx.log(ngx.ERR, err)
 else
     ngx.say(res:read_body())
 end
```

We could look at making more of the functions module level, so they're available as utilities (`_format_request` for example). That way, you'd populate your params table manually, then use `_format_request` to get something valid to send down the wire, then pass the same params table to `read_response`.

In my example, I send an empty params table to `read_response` as it's expecting an inner headers table.

**Comment by thefosk** [comment]
Yep, that works too.

**Pull request closed without merging**
