### PR TITLE
add rockspec

### PR DESCRIPTION
**Pull request by DorianGray**
This adds the rockspec I used to deploy lua-resty-http to luarocks under the olivine-labs account. Let me know if you'd like to take over administration of this rock or if I should just make pull requests periodically =)

### CODE REVIEW

**Comment by istr** [comment]
+1: Please pull this; would be great to have the (obviously still actively maintained) original package as a rock, not a fork... https://luarocks.org/modules/olivine-labs/lua-resty-http

**Comment by pintsized** [comment]
Sorry, yes, I've been meaning to do this. If there was a pull request with all the correct metadata (including the URI for the latest release) I'd just merge it! Otherwise, I'll get around to doing it soon.

**Comment by istr** [comment]
Ok. Please have a look at PR https://github.com/pintsized/lua-resty-http/pull/34.

**Comment by pintsized** [comment]
Merged as per #36

**Comment by istr** [comment]
Thanks a lot for merging. To make it "world usable" you still need to transfer "ownership" of the module within the [luarocks root manifest](https://luarocks.org/m/root)
- @pintsized needs to [register at luarocks](https://luarocks.org), [connect the github account](https://luarocks.org/settings) and ["claim" the module](https://luarocks.org/github/claim)
- maybe @DorianGray needs to delete the module that exists in the root manifest (but I am unsure if it is necessary)

That's a thing a third party (me) can't do... ;-)
Thanks for your support and for providing this great module.

**Comment by pintsized** [comment]
Ah, I see! (I've not used luarocks, as you can probably tell). I've registered and connected my github account, but it says there aren't any modules I can claim. I think you're right, the existing lua-resty-http needs to be removed first.

**Comment by istr** [comment]
Yes, I used to refrain from using it for a very long time (because the older luarocks versions were rather buggy and the old luarocks server had lots of downtime(s)). But this changed fundamentally since the 
[announced merge of moonrocks with luarocks](http://sourceforge.net/p/luarocks/mailman/message/32369512/) became reality with @leafo as [the current maintainer of luarocks.org](https://github.com/leafo/luarocks-site).
Maybe you need to upload a copy of the rockspec within your own luarocks account to be able to claim the package; I am not (yet) a power user of the luarocks.org page, either. ;-)

**Comment by leafo** [comment]
The claim system only works if there is a copy of the module controlled by the [luarocks account](https://luarocks.org/modules/luarocks). The luarocks account was created to hold all the auto-imported modules from the old default luarocks.org manifest. If you were never a user of the old luarocks manifest you won't have any modules available for claiming. You'll have to upload your module the regular way: through the `luarocks upload` command or the web interface.

This claim module system will be removed shortly as most people have migrated over to the new luarocks.org. Additionally better github integration is definitely something I'd like to spend more time on.

**Comment by DorianGray** [comment]
@pintsized I've deleted the olivine-labs deployed version of lua-resty-http. Please deploy the new version ASAP.

**Comment by pintsized** [comment]
Thanks all, it's there now: https://luarocks.org/modules/pintsized/lua-resty-http

**Comment by pintsized** [comment]
Sorry if this is covered elsewhere, but for future releases, do I need to rename the rockspec file and re-upload it to keep version numbers in sync? That is, does the version number have to be in the rockspec file name?

**Comment by istr** [comment]
Thanks for the rock... Confirmed to work for me.

```
luarocks install lua-resty-http
Installing https://luarocks.org/lua-resty-http-0.06-0.src.rock...
Using https://luarocks.org/lua-resty-http-0.06-0.src.rock... switching to 'build' mode
Updating manifest for [...]
lua-resty-http 0.06-0 is now built and installed in [...] (license: 2-clause BSD)
```

And yes, [you need to rename and keep filename and version within the rockspec in sync](https://github.com/keplerproject/luarocks/wiki/Creating-a-rock).
If you leave out the version from the filename luarocks complains
```Error: Expected filename in format 'name-version-revision.rockspec'.```
If filename and contents mismatch luarocks complains, e.g.
```Error: Inconsistency between rockspec filename (cdb-1.0-0.rockspec) and its contents (cdb-1.0-1.rockspec).```

So the upgrade procedure is:
- rename rockspec
- change version in rockspec
- tag new version
- push to github
- ```luarocks upload --api-key={key} lua-resty-http-{version}-{revision}.rockspec```
  (luarocks.org will automatically pull the tagged version from github and build the rock)

**Comment by pintsized** [comment]
That's great, thanks.

**Comment by drsnyder** [comment]
> @pintsized I've deleted the olivine-labs deployed version of lua-resty-http. Please deploy the new version ASAP.

Can the existing olivine-labs versions be transferred over to the @pintsized luarocks repo? We had pinned to the 0.1-0 version of this rock because there were some changes in 0.2-0 that affected our dependencies when testing and also caused some connectivity issues.

**Comment by pintsized** [comment]
Hi. I'm not sure how that would work - do you know which tag was this referencing? v0.02? There have been many important bug fixes since then, and certainly no known issues affecting connectivity etc - I'd much rather help you get onto the latest version... Can you describe the problems you're having (perhaps in a fresh Issue)?

**Pull request closed without merging**
